// Re-exported from @derekentringer/ns-shared for backward compatibility
export type {
  Note,
  CreateNoteRequest,
  UpdateNoteRequest,
  NoteListResponse,
  NoteSortField,
  FolderSortField,
  SortOrder,
  FolderInfo,
  FolderListResponse,
  CreateFolderRequest,
  MoveFolderRequest,
  ReorderFoldersRequest,
  ReorderNotesRequest,
  TagInfo,
  TagListResponse,
  NoteSearchResult,
  SyncChange,
  SyncCursor,
  SyncPushRequest,
  SyncPullResponse,
  AiCompleteRequest,
  AiSummarizeRequest,
  AiSuggestTagsRequest,
  AiSuggestTagsResponse,
  EmbeddingStatus,
  AudioMode,
  TranscribeResponse,
  QASource,
  BacklinkInfo,
  BacklinksResponse,
  NoteTitleEntry,
  NoteTitlesResponse,
  NoteVersion,
  NoteVersionListResponse,
} from "@derekentringer/ns-shared";
