-- Drop the old non-partial unique index on folders(parentId, name).
-- This index was auto-generated by Prisma from @@unique([userId, parentId, name])
-- but doesn't exclude soft-deleted rows (no WHERE deletedAt IS NULL filter).
-- It prevents re-creating folders with the same name after soft-deletion.
--
-- The correct partial indexes were added in migration 20260312100000:
--   folders_root_name_key: UNIQUE (userId, name) WHERE parentId IS NULL AND deletedAt IS NULL
--   folders_userId_parentId_name_key: UNIQUE (userId, parentId, name) WHERE deletedAt IS NULL
--
-- Those partial indexes correctly enforce uniqueness only among active folders.

DROP INDEX IF EXISTS "folders_parentId_name_key";
