ALTER TABLE notes ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE notes ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE notes ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN deleted_at TEXT;
ALTER TABLE notes ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'pending';
